name: Documentation Issue
description: Report an issue with documentation, examples, or vignettes
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve batr's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - Function help page (?function_name)
        - Vignette
        - README
        - Code example
        - Error message
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Which function, vignette, or file is affected?
      placeholder: e.g., ?summary_table, vignette("custom-reports"), README.md
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's unclear, incorrect, or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How could this be improved or clarified?
