name: Feature Request
description: Suggest a new feature or enhancement for batr
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you're looking for.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe what you're trying to accomplish.
      placeholder: I'm frustrated when... / I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: A new function that... / An option to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New function
        - Enhancement to existing function
        - New plot type
        - Report template feature
        - Data import feature
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Use Case
      description: Provide an example of how you would use this feature.
      placeholder: |
        ```r
        # Example code showing desired usage
        
        ```
      render: r

  - type: checkboxes
    id: willing-to-help
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
